# Copyright 2025 The OpenSSL Project Authors. All Rights Reserved.
#
# Licensed under the Apache License 2.0 (the "License").  You may not use
# this file except in compliance with the License.  You can obtain a copy
# in the file LICENSE in the source distribution or at
# https://www.openssl.org/source/license.html

name: Cross Compile LoongArch64

on: [pull_request, push]

jobs:
  cross-compilation-LoongArch64:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - { toolchain-version: 2023.08.08 }
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache/restore@v4
        id: restore-cache
        with:
          path: /opt/cross-tools
          key: loongarch64-${{ matrix.platform.toolchain-version }}

      - name: Download LoongArch64 gcc+glibc toolchain
        if: ${{ !steps.restore-cache.outputs.cache-hit }}
        run: |
          url="https://github.com/loongson/build-tools/releases/download/${{ matrix.platform.toolchain-version }}/x86_64-cross-tools-loongarch64-gcc-libc.tar.xz"

          wget "$url" -O /tmp/toolchain.tar.xz

          mkdir -p /opt
          tar -C /opt -x -f /tmp/toolchain.tar.xz

      - uses: actions/cache/save@v3
        if: ${{ !steps.restore-cache.outputs.cache-hit }}
        with:
          path: /opt/cross-tools
          key: loongarch64-${{ matrix.platform.toolchain-version }}

      - name: setup Loongarch64 build environment
        run: |
          echo "/opt/cross-tools/bin" >> $GITHUB_PATH
          echo "CC=loongarch64-unknown-linux-gnu-gcc" >> $GITHUB_ENV
          echo "CXX=loongarch64-unknown-linux-gnu-g++" >> $GITHUB_ENV
          echo "AS=loongarch64-unknown-linux-gnu-as" >> $GITHUB_ENV

      - name: config with FIPS
        run: |
          ./config --banner=Configured --strict-warnings enable-fips \
                   --cross-compile-prefix="/opt/cross-tools/bin"

      - name: config dump
        run: ./configdata.pm --dump

      - name: make
        run: make -s -j4
